In [ ]:
import numpy as np 

In [5]:
# Rank 1 array

In [6]:
arr1 = [2,2,3,4,5,6]
print(type(arr1))

<class 'list'>


In [7]:
narr1=np.array(arr1)
print(type(narr1))

<class 'numpy.ndarray'>


In [16]:
# multidimensional array
 
arr2 = [[1,2,3,4,5],[6,7,8,9,10]]
narr2=np.array(arr2)
print(narr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [17]:
print (narr2.shape)

(2, 5)


In [21]:
hey = np.eye(3,3)
print(hey)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8]) 
print(x*y)

[ 5 12 21 32]


In [28]:
z = x*y

In [18]:
print('axes:', x.ndim)
print('shape:', x.shape)
print('size:', x.size)
print('data type:',x.dtype)

axes: 1
shape: (4,)
size: 4
data type: int32


In [23]:
print(x+y)

[ 6  8 10 12]


In [24]:
print(x+4)

[5 6 7 8]


In [25]:
print(x-y)

[-4 -4 -4 -4]


In [26]:
print(y-x)

[4 4 4 4]


In [27]:
print(y-3)

[2 3 4 5]


In [28]:
print(x*y)

[ 5 12 21 32]


In [29]:
print(np.dot(y,x))

70


In [31]:
print (5+12+21+32)

70


In [32]:
print(y/x)

[5.         3.         2.33333333 2.        ]


In [33]:
print(x/y)

[0.2        0.33333333 0.42857143 0.5       ]


In [44]:
import numpy as np
x = np.matrix([[1,2],[3,4]])
y = np.matrix([[5,6],[7,8]])
print (x.I)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [41]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print (x)
print (y)
print(x*y)
print(x**3)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]
[[ 1  8]
 [27 64]]


In [4]:
print(type(x))

<class 'numpy.matrix'>


In [45]:
print(x.I)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
print(y)

[[5 6]
 [7 8]]


In [8]:
print(x+y)

[[ 6  8]
 [10 12]]


In [22]:
import numpy as np

a = np.array([[1,2],[-3,4]])
b = np.array([4,-1])
print (a)
print (b)
ainv = np.linalg.inv(a)
ainv.dot(b)


[[ 1  2]
 [-3  4]]
[ 4 -1]


array([1.8, 1.1])

In [ ]:
import nump as np

In [24]:
arr = [[1,2,3,4],[3,4,5,6],[7,8,9,6],[12,7,10,9],[2,11,8,10]]

narr = np.array(arr) # convert array into  numpy array 

print (narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9  6]
 [12  7 10  9]
 [ 2 11  8 10]]


In [25]:
narr.sum() # sum all the values of the array 

127

In [34]:
narr.sum(axis=0)  # column wise sum 


array([10, 18, 30, 38, 31])

In [35]:
narr.sum(axis=1) # row wise sum

array([10, 18, 30, 38, 31])

In [36]:
narr.mean(axis=0) # column mean 

array([5. , 6.4, 7. , 7. ])

In [37]:
narr.mean(axis=1) #column mean

array([2.5 , 4.5 , 7.5 , 9.5 , 7.75])

In [40]:
np.median(narr,axis=0) 

array([3., 7., 8., 6.])